// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getControls = `-- name: GetControls :one
select user_id, allow_explicit, excluded_tracks, excluded_artists, excluded_genres, postponed_tracks
from user_controls
where user_id = $1
`

type GetControlsRow struct {
	UserID          string `json:"user_id"`
	AllowExplicit   bool   `json:"allow_explicit"`
	ExcludedTracks  []byte `json:"excluded_tracks"`
	ExcludedArtists []byte `json:"excluded_artists"`
	ExcludedGenres  []byte `json:"excluded_genres"`
	PostponedTracks []byte `json:"postponed_tracks"`
}

func (q *Queries) GetControls(ctx context.Context, userID string) (GetControlsRow, error) {
	row := q.db.QueryRow(ctx, getControls, userID)
	var i GetControlsRow
	err := row.Scan(
		&i.UserID,
		&i.AllowExplicit,
		&i.ExcludedTracks,
		&i.ExcludedArtists,
		&i.ExcludedGenres,
		&i.PostponedTracks,
	)
	return i, err
}

const getTracksByIDs = `-- name: GetTracksByIDs :many
select id, title, artist, album, genres, release_date, duration_ms, popularity,
    explicit, features, external, created_at, updated_at, commercial_boost, quality_penalty, discovery_allowed
from tracks
where id = any($1::text[])
order by id
`

type GetTracksByIDsRow struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Album            string             `json:"album"`
	Genres           []byte             `json:"genres"`
	ReleaseDate      string             `json:"release_date"`
	DurationMs       int32              `json:"duration_ms"`
	Popularity       float64            `json:"popularity"`
	Explicit         bool               `json:"explicit"`
	Features         []byte             `json:"features"`
	External         []byte             `json:"external"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CommercialBoost  float64            `json:"commercial_boost"`
	QualityPenalty   float64            `json:"quality_penalty"`
	DiscoveryAllowed bool               `json:"discovery_allowed"`
}

func (q *Queries) GetTracksByIDs(ctx context.Context, dollar_1 []string) ([]GetTracksByIDsRow, error) {
	rows, err := q.db.Query(ctx, getTracksByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTracksByIDsRow
	for rows.Next() {
		var i GetTracksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Genres,
			&i.ReleaseDate,
			&i.DurationMs,
			&i.Popularity,
			&i.Explicit,
			&i.Features,
			&i.External,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommercialBoost,
			&i.QualityPenalty,
			&i.DiscoveryAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentInteractions = `-- name: ListRecentInteractions :many
select user_id, track_id, type, weight, occurred_at, context, completed_ms
from interactions
where occurred_at >= now() - interval '365 days'
order by occurred_at desc
limit 250000
`

type ListRecentInteractionsRow struct {
	UserID      string             `json:"user_id"`
	TrackID     string             `json:"track_id"`
	Type        string             `json:"type"`
	Weight      float64            `json:"weight"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Context     []byte             `json:"context"`
	CompletedMs int32              `json:"completed_ms"`
}

func (q *Queries) ListRecentInteractions(ctx context.Context) ([]ListRecentInteractionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentInteractions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentInteractionsRow
	for rows.Next() {
		var i ListRecentInteractionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.TrackID,
			&i.Type,
			&i.Weight,
			&i.OccurredAt,
			&i.Context,
			&i.CompletedMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
select id, title, artist, album, genres, release_date, duration_ms, popularity,
    explicit, features, external, created_at, updated_at, commercial_boost, quality_penalty, discovery_allowed
from tracks
order by id
`

type ListTracksRow struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Album            string             `json:"album"`
	Genres           []byte             `json:"genres"`
	ReleaseDate      string             `json:"release_date"`
	DurationMs       int32              `json:"duration_ms"`
	Popularity       float64            `json:"popularity"`
	Explicit         bool               `json:"explicit"`
	Features         []byte             `json:"features"`
	External         []byte             `json:"external"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CommercialBoost  float64            `json:"commercial_boost"`
	QualityPenalty   float64            `json:"quality_penalty"`
	DiscoveryAllowed bool               `json:"discovery_allowed"`
}

func (q *Queries) ListTracks(ctx context.Context) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Genres,
			&i.ReleaseDate,
			&i.DurationMs,
			&i.Popularity,
			&i.Explicit,
			&i.Features,
			&i.External,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommercialBoost,
			&i.QualityPenalty,
			&i.DiscoveryAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordInteraction = `-- name: RecordInteraction :exec
insert into interactions (user_id, track_id, type, weight, occurred_at, context, completed_ms)
values ($1, $2, $3, $4, $5, $6::jsonb, $7)
`

type RecordInteractionParams struct {
	UserID      string             `json:"user_id"`
	TrackID     string             `json:"track_id"`
	Type        string             `json:"type"`
	Weight      float64            `json:"weight"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Column6     []byte             `json:"column_6"`
	CompletedMs int32              `json:"completed_ms"`
}

func (q *Queries) RecordInteraction(ctx context.Context, arg RecordInteractionParams) error {
	_, err := q.db.Exec(ctx, recordInteraction,
		arg.UserID,
		arg.TrackID,
		arg.Type,
		arg.Weight,
		arg.OccurredAt,
		arg.Column6,
		arg.CompletedMs,
	)
	return err
}

const upsertControls = `-- name: UpsertControls :exec
insert into user_controls (user_id, allow_explicit, excluded_tracks, excluded_artists, excluded_genres, postponed_tracks)
values ($1, $2, $3::jsonb, $4::jsonb, $5::jsonb, $6::jsonb)
on conflict (user_id) do update set
    allow_explicit = excluded.allow_explicit,
    excluded_tracks = excluded.excluded_tracks,
    excluded_artists = excluded.excluded_artists,
    excluded_genres = excluded.excluded_genres,
    postponed_tracks = excluded.postponed_tracks,
    updated_at = now()
`

type UpsertControlsParams struct {
	UserID        string `json:"user_id"`
	AllowExplicit bool   `json:"allow_explicit"`
	Column3       []byte `json:"column_3"`
	Column4       []byte `json:"column_4"`
	Column5       []byte `json:"column_5"`
	Column6       []byte `json:"column_6"`
}

func (q *Queries) UpsertControls(ctx context.Context, arg UpsertControlsParams) error {
	_, err := q.db.Exec(ctx, upsertControls,
		arg.UserID,
		arg.AllowExplicit,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
insert into tracks (
    id, title, artist, album, genres, release_date, duration_ms, popularity,
    explicit, features, external, commercial_boost, quality_penalty, discovery_allowed
) values (
    $1, $2, $3, $4, $5::jsonb, $6, $7, $8,
    $9, $10::jsonb, $11::jsonb, $12, $13, $14
)
on conflict (id) do update set
    title = excluded.title,
    artist = excluded.artist,
    album = excluded.album,
    genres = excluded.genres,
    release_date = excluded.release_date,
    duration_ms = excluded.duration_ms,
    popularity = excluded.popularity,
    explicit = excluded.explicit,
    features = excluded.features,
    external = excluded.external,
    commercial_boost = excluded.commercial_boost,
    quality_penalty = excluded.quality_penalty,
    discovery_allowed = excluded.discovery_allowed,
    updated_at = now()
`

type UpsertTrackParams struct {
	ID               string  `json:"id"`
	Title            string  `json:"title"`
	Artist           string  `json:"artist"`
	Album            string  `json:"album"`
	Column5          []byte  `json:"column_5"`
	ReleaseDate      string  `json:"release_date"`
	DurationMs       int32   `json:"duration_ms"`
	Popularity       float64 `json:"popularity"`
	Explicit         bool    `json:"explicit"`
	Column10         []byte  `json:"column_10"`
	Column11         []byte  `json:"column_11"`
	CommercialBoost  float64 `json:"commercial_boost"`
	QualityPenalty   float64 `json:"quality_penalty"`
	DiscoveryAllowed bool    `json:"discovery_allowed"`
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.Exec(ctx, upsertTrack,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Column5,
		arg.ReleaseDate,
		arg.DurationMs,
		arg.Popularity,
		arg.Explicit,
		arg.Column10,
		arg.Column11,
		arg.CommercialBoost,
		arg.QualityPenalty,
		arg.DiscoveryAllowed,
	)
	return err
}
