// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ImportJob struct {
	ID             string             `json:"id"`
	Provider       string             `json:"provider"`
	SourceType     string             `json:"source_type"`
	SourceValue    string             `json:"source_value"`
	Market         string             `json:"market"`
	Status         string             `json:"status"`
	ImportedTracks int32              `json:"imported_tracks"`
	UpdatedTracks  int32              `json:"updated_tracks"`
	Skipped        int32              `json:"skipped"`
	Warnings       []byte             `json:"warnings"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Interaction struct {
	ID          int64              `json:"id"`
	UserID      string             `json:"user_id"`
	TrackID     string             `json:"track_id"`
	Type        string             `json:"type"`
	Weight      float64            `json:"weight"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Context     []byte             `json:"context"`
	CompletedMs int32              `json:"completed_ms"`
}

type ProviderCache struct {
	Provider  string             `json:"provider"`
	ItemType  string             `json:"item_type"`
	ItemID    string             `json:"item_id"`
	Market    string             `json:"market"`
	Payload   []byte             `json:"payload"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LastError pgtype.Text        `json:"last_error"`
}

type Track struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Album            string             `json:"album"`
	Genres           []byte             `json:"genres"`
	ReleaseDate      string             `json:"release_date"`
	DurationMs       int32              `json:"duration_ms"`
	Popularity       float64            `json:"popularity"`
	Explicit         bool               `json:"explicit"`
	Features         []byte             `json:"features"`
	External         []byte             `json:"external"`
	CommercialBoost  float64            `json:"commercial_boost"`
	QualityPenalty   float64            `json:"quality_penalty"`
	DiscoveryAllowed bool               `json:"discovery_allowed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TrackEnrichment struct {
	TrackID                string             `json:"track_id"`
	Provider               string             `json:"provider"`
	MusicbrainzRecordingID string             `json:"musicbrainz_recording_id"`
	MusicbrainzArtistID    string             `json:"musicbrainz_artist_id"`
	Isrc                   string             `json:"isrc"`
	Payload                []byte             `json:"payload"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type UserControl struct {
	UserID          string             `json:"user_id"`
	AllowExplicit   bool               `json:"allow_explicit"`
	ExcludedTracks  []byte             `json:"excluded_tracks"`
	ExcludedArtists []byte             `json:"excluded_artists"`
	ExcludedGenres  []byte             `json:"excluded_genres"`
	PostponedTracks []byte             `json:"postponed_tracks"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
